# See https://docs.travis-ci.com/user/multi-os/ for more info.

# Example as single section.
#os:
#- linux
#- osx
#- cpp
#compiler:
#- gcc
#install:
#if [[ "$os" == "linux" ]]; then sudo apt-get -qq update; sudo apt-get -qq install library; fi
#if [[ "$os" == "osx" ]]; then brew doctor; brew library; f
#script:
#- ./autogen.sh && ./configure && make

# Multi-section
os:
- linux
sudo: required
dist: trusty
language:
- cpp
compiler:
#-clang
- gcc
before_install:
#- sudo apt-get update
#- sudo apt-get -qq install packagecloud.io/github/git-lfs
- git lfs init
install:
# Get the LFS'ed file 'cos clone happened before LFS init.
- git checkout other_lib
- git lfs logs
- sudo apt-get -qq update; sudo apt-get -qq install doxygen
- cd ../..
- git clone https://github.com/msc-/gyp
- cd gyp && sudo ./setup.py install && cd ..
- cd KhronosGroup/KTX
- ls -l other_lib/linux/Debug-x64
script:
- cd build/make/linux && make BUILDTYPE=Debug
- make BUILDTYPE=Release

---

os:
- osx
osx_image:
- xcode7.2
language:
- cpp
compiler:
- clang
#- gcc
install:
- port install doxygen
script:
- cd build/xcode/mac
- xcodebuild -project ktxtests -alltargets -configuration Debug
- xcodebuild -project ktxtests -alltargets -configuration Release
- xcodebuild -project ktxtools -alltargets -configuration Debug
- xcodebuild -project ktxtools -alltargets -configuration Release
- cd ../ios
- xcodebuild -project ktxtests -alltargets -configuration Debug
- xcodebuild -project ktxtests -alltargets -configuration Release
- xcodebuild -project ktxtools -alltargets -configuration Debug
- xcodebuild -project ktxtools -alltargets -configuration Release

