# See https://docs.travis-ci.com/user/multi-os/ for more info.

# Example as single section.
#os:
#- linux
#- osx
#- cpp
#compiler:
#- gcc
#install:
#if [[ "$os" == "linux" ]]; then sudo apt-get -qq update; sudo apt-get -qq install library; fi
#if [[ "$os" == "osx" ]]; then brew doctor; brew library; f
#script:
#- ./autogen.sh && ./configure && make

# Multi-section
os:
- linux
sudo: required
dist: trusty
language:
- cpp
compiler:
#-clang
- gcc
before_install:
# Current directory is .../build/KhronosGroup/KTX. Go up to build.
- pushd ../..
# The already installed GIT LFS is very old - 0.5.0. Need a more recent
# one to work with the GitHub server.
- wget https://github.com/github/git-lfs/releases/download/v1.1.0/git-lfs-linux-amd64-1.1.0.tar.gz
- tar -zxvf git-lfs-linux-amd64-1.1.0.tar.gz
- export PATH=`pwd`/git-lfs-1.1.0:$PATH
- git lfs install
# popd back to the cloned repo.
- popd
- git lfs pull --include="other_lib/linux/Debug-x64/libSDL2-2.0.so.0.4.0"
install:
- sudo apt-get -qq update; sudo apt-get -qq install doxygen
- pushd ../..
- git clone https://github.com/msc-/gyp
- cd gyp && sudo ./setup.py install && cd ..
- popd
- ls -l other_lib/linux/Debug-x64
script:
- cd build/make/linux
- make BUILDTYPE=Debug
- make BUILDTYPE=Release

---

os:
- osx
osx_image:
- xcode7.2
language:
- cpp
compiler:
- clang
#- gcc
install:
- port install doxygen
script:
- cd build/xcode/mac
- xcodebuild -project ktxtests -alltargets -configuration Debug
- xcodebuild -project ktxtests -alltargets -configuration Release
- xcodebuild -project ktxtools -alltargets -configuration Debug
- xcodebuild -project ktxtools -alltargets -configuration Release
- cd ../ios
- xcodebuild -project ktxtests -alltargets -configuration Debug
- xcodebuild -project ktxtests -alltargets -configuration Release
- xcodebuild -project ktxtools -alltargets -configuration Debug
- xcodebuild -project ktxtools -alltargets -configuration Release
